theme: jekyll-theme-cayman
lang: en
author:
  name: Matthias Humt
  url: https://github.com/hummat
social:
  name: Matthias Humt
  links:
    - https://twitter.com/matthiashumt
    - https://www.linkedin.com/in/matthiashumt
    - https://github.com/hummat
twitter:
  username: matthiashumt
  card: summary_large_image
logo: https://avatars.githubusercontent.com/u/22399283?v=4
defaults:
  - scope:
      path: ""
    values:
      image: https://repository-images.githubusercontent.com/1120503046/8ba4e2ed-30ef-4d0d-996f-68a48962cb9b
plugins:
  - jekyll-sitemap
  - jekyll-feed
